build-last-errors="[]"
build-last-errors-base-dir="~/Desktop/Dissertation/myPack/myStable/"
build-last-outputs="[{\"output\":\"==> R CMD INSTALL --no-multiarch --with-keep.source myStable\\n\\n\",\"type\":0},{\"output\":\"* installing to library ‘/Users/air/Library/R/3.3/library’\\n\",\"type\":1},{\"output\":\"* installing *source* package ‘jStable’ ...\\n\",\"type\":1},{\"output\":\"\",\"type\":1},{\"output\":\"clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/local/Library/Frameworks/R.framework/Resources/lib -L/opt/local/lib -Wl,-headerpad_max_install_names -o jStable.so stable.o -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation\\n\",\"type\":1},{\"output\":\"\",\"type\":1},{\"output\":\"** libs\\n\",\"type\":1},{\"output\":\"\",\"type\":1},{\"output\":\"installing to /Users/air/Library/R/3.3/library/jStable/libs\\n\",\"type\":1},{\"output\":\"\",\"type\":1},{\"output\":\"** R\\n\",\"type\":1},{\"output\":\"** preparing package for lazy loading\\n\",\"type\":1},{\"output\":\"\",\"type\":1},{\"output\":\"No man pages found in package  ‘jStable’ \\n\",\"type\":1},{\"output\":\"\",\"type\":1},{\"output\":\"** help\\n\",\"type\":1},{\"output\":\"*** installing help indices\\n\",\"type\":1},{\"output\":\"\",\"type\":1},{\"output\":\"** building package indices\\n\",\"type\":1},{\"output\":\"** testing if installed package can be loaded\\n\",\"type\":1},{\"output\":\"\",\"type\":1},{\"output\":\"* DONE (jStable)\\n\",\"type\":1},{\"output\":\"\",\"type\":1}]"
compile_pdf_state="{\"errors\":[],\"output\":\"\",\"running\":false,\"tab_visible\":false,\"target_file\":\"\"}"
console_procs="[{\"buffered_output\":\"To https://github.com/jansila/myStable_backup.git\\n ! [rejected]        master -> master (fetch first)\\nerror: failed to push some refs to 'https://github.com/jansila/myStable_backup.git'\\nhint: Updates were rejected because the remote contains work that you do\\nhint: not have locally. This is usually caused by another repository pushing\\nhint: to the same ref. You may want to first integrate the remote changes\\nhint: (e.g., 'git pull ...') before pushing again.\\nhint: See the 'Note about fast-forwards' in 'git push --help' for details.\\n\",\"caption\":\"Git Push\",\"dialog\":true,\"exit_code\":1,\"handle\":\"03eb62d3b50a4edd9c8a02bbd11bd733\",\"interaction_mode\":0,\"max_output_lines\":500,\"show_on_output\":false}]"
files.monitored-path=""
find-in-files-state="{\"handle\":\"\",\"input\":\"\",\"path\":\"\",\"regex\":true,\"results\":{\"file\":[],\"line\":[],\"lineValue\":[],\"matchOff\":[],\"matchOn\":[]},\"running\":false}"
imageDirtyState="1"
saveActionState="-1"
